# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    user: $UID:$GID
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./data/storage:/flightlessmango/storage
      - ./docker-storage.yml:/flightlessmango/config/storage.yml:ro
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: example
      REDIS_URL: redis://redis:6379/1
